### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by bradfeehan** [pda/aws-keychain#8]
I've created a [formula]. At the moment it's just in my personal formulae repo, but maybe you should own it? :smile:

[formula]: <https://github.com/bradfeehan/homebrew-formulae/blob/master/aws-keychain.rb>

**Comment by pda** [comment]
Nice :+1:  However:

* I personally am never likely to install via Homebrew, since I'll always have it symlinked to my dev repo. So I'm not a user of this formula.
* If it's ever to be submitted to the main Homebrew repo, it [should not be self-submitted](https://github.com/Homebrew/homebrew/blob/d39c02fc9689b886a2d2b6d56f0fd7abbcdfc501/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) (nor niche, which it probably is).
